# Generated by Django 5.1.7 on 2026-06-04 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Legenda')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Descrição curta')),
                ('property_type', models.CharField(choices=[('standard', 'Padrão'), ('luxury', 'Luxo'), ('penthouse', 'Cobertura'), ('commercial', 'Comercial'), ('land', 'Terreno')], default='luxury', max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(default='Porto Belo', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='SC', max_length=50, verbose_name='Estado')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quartos')),
                ('suites', models.PositiveIntegerField(blank=True, null=True, verbose_name='Suítes')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Banheiros')),
                ('garage_spots', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas de garagem')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área total (m²)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mari Corretora', max_length=100, verbose_name='Nome do Site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logotipo')),
                ('whatsapp_number', models.CharField(default='+554788562089', max_length=20, verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('hero_title', models.CharField(default='Imóveis de Alto Padrão em Porto Belo e Itapema', max_length=200, verbose_name='Título do Hero')),
                ('hero_subtitle', models.CharField(default='Exclusividade e sofisticação no litoral catarinense', max_length=300, verbose_name='Subtítulo do Hero')),
                ('hero_cta_text', models.CharField(default='Fale com Mari no WhatsApp', max_length=100, verbose_name='Texto do Botão CTA')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('about_title', models.CharField(default='Por que investir aqui', max_length=200, verbose_name="Título 'Sobre'")),
                ('about_text', models.TextField(blank=True, verbose_name="Texto 'Sobre'")),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('text', models.TextField(verbose_name='Depoimento')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos dos Imóveis',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
